# This action builds the alpha version as apk on a password protected zip,
# and uploads it to the alpha release.
# Adapted from https://github.com/amirisback/automated-build-android-app-with-github-action
name: Build alpha apk

on:
  # Triggers the workflow on push events for the master branch
  # push:
  #   branches:
  #     - master

  # Run this workflow manually from the Actions tab
  workflow_dispatch:

# parameters
env:
  VARIANT: alpha
  TAG: alpha
  ZIP: app-alpha.zip

permissions:
  contents: write # need to update tag and release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository files
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build & assemble
        run: ./gradlew build assemble${{ env.VARIANT }}

      - name: Zip ${{ env.VARIANT }} apk as ${{ env.ZIP }}
        # just remove the password here if you want to build the apk yourself instead of sponsoring me and getting it as a benefit :(
        run: zip -j -P ${{ secrets.ALPHA_PASS }} ${{ env.ZIP }} app/build/outputs/apk/${{ env.VARIANT }}/*.apk

      - name: Update ${{ env.TAG }} tag to current commit
        run: |
          git tag --force ${{ env.TAG }}
          git push --force origin tag ${{ env.TAG }}

      - name: Upload ${{ env.ZIP }} to ${{ env.TAG }} release
        run: |
          gh release upload ${{ env.TAG }} ${{ env.ZIP }} --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
